version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "9191:9191"
    volumes:
      - "/usr/app/node_modules"
      - ".:/usr/app"  
    environment:
      - "POSTGRES_HOST=localhost"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=postgres_password"
      - "POSTGRES_DB=simple_blog_api"
      - "PORT=9191"